---
title: "summary"
author: "Jia Yuhan"
output: 
  html_document:
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r ,fig.width=12, fig.height=7,echo=F}

library(kableExtra)
```


# 500
```{r ,fig.width=12, fig.height=7,echo=F}

load(file = "summary_navie_ci_ns500_OM.rdata")
betat=True_T_param$beta_t_dagger
source(file = "evalua.R")

```

## OM1
```{r,results='asis',echo=F }

i=1 

    res1 <- evalua(res = reslist[[i]], beta_t = betat)[[1]][,-c(9:20,25)]
    

    kable(res1, format = "html", booktabs = TRUE) %>%
      kable_styling(full_width = FALSE) %>%
      add_header_above(c("-"=4,"ITSA" = 5, "Naive" = 5)) %>%
      column_spec(1, width = "5em") %>%
      column_spec(2, width = "8em")%>%print
    
    cat("\n")
    
    res2 <- evalua(res =reslist[[i]], beta_t = betat)[[2]]
    
    kable(res2, format = "html", booktabs = TRUE) %>%
      kable_styling(full_width = FALSE) %>%
      add_header_above(c("-"=3,"Naive" = 5, "ITSA" = 5)) %>%
      column_spec(1, width = "5em") %>%
      column_spec(2, width = "8em")%>%print
    

    cat("\n")
   


```


## OM2
```{r,results='asis',echo=F }


i=2 
    res1 <- evalua(res = reslist[[i]], beta_t = betat)[[1]][,-c(9:20,25)]
    
  
    kable(res1, format = "html", booktabs = TRUE) %>%
      kable_styling(full_width = FALSE) %>%
      add_header_above(c("-"=4,"ITSA" = 5, "Naive" = 5)) %>%
      column_spec(1, width = "5em") %>%
      column_spec(2, width = "8em")%>%print
    
    cat("\n")
    
    res2 <- evalua(res =reslist[[i]], beta_t = betat)[[2]]
    
    kable(res2, format = "html", booktabs = TRUE) %>%
      kable_styling(full_width = FALSE) %>%
      add_header_above(c("-"=3,"Naive" = 5, "ITSA" = 5)) %>%
      column_spec(1, width = "5em") %>%
      column_spec(2, width = "8em")%>%print
    

    cat("\n")
   



```
